### ISSUE TITLE
[Bug]: Following "Deploy in a pre-constructed private network (for proxies etc)" results in error

### ISSUE THREAD

**Issue by awgeorge** [kube-hetzner/terraform-hcloud-kube-hetzner#1758]
### Description

When setting `existing_network_id = [hcloud_network.k3s_proxied.id]` as defined in the readme, the following error occurs while running `terraform plan` or `terraform apply`

```
 Error: Invalid count argument
│ 
│   on .terraform/modules/kube-hetzner/modules/host/main.tf line 155, in resource "hcloud_server_network" "server":
│  155:   count     = var.network_id > 0 ? 0 : 1
│ 
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to
│ first apply only the resources that the count depends on.
```

### Kube.tf file

```terraform
resource "hcloud_network" "k3s_proxied" {
  name     = "k3s-proxied"
  ip_range = "10.0.0.0/8"
}

resource "hcloud_network_subnet" "k3s_proxy" {
  network_id   = hcloud_network.k3s_proxied.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.128.0.0/9"
}
resource "hcloud_server" "your_proxy_server" {
  ...
}
resource "hcloud_server_network" "your_proxy_server" {
  depends_on = [
    hcloud_server.your_proxy_server
  ]
  server_id  = hcloud_server.your_proxy_server.id
  network_id = hcloud_network.k3s_proxied.id
  ip         = "10.128.0.1"
}
module "kube-hetzner" {
  ...
  existing_network_id = [hcloud_network.k3s_proxied.id]
  network_ipv4_cidr = "10.0.0.0/9"
  additional_k3s_environment = {
    "http_proxy" : "http://10.128.0.1:3128",
    "HTTP_PROXY" : "http://10.128.0.1:3128",
    "HTTPS_PROXY" : "http://10.128.0.1:3128",
    "CONTAINERD_HTTP_PROXY" : "http://10.128.0.1:3128",
    "CONTAINERD_HTTPS_PROXY" : "http://10.128.0.1:3128",
    "NO_PROXY" : "127.0.0.0/8,10.0.0.0/8,",
  }
}
```

### Screenshots

<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/697d041c-a036-4498-a3a1-eab51d7c3338" />

### Platform

Mac

**Comment by mysticaltech** [comment]
This should have been fixed in [the current version.](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/releases/tag/v2.17.2)

**Comment by alexandradeas** [comment]
hey @mysticaltech I'm still getting this on both `2.17.2` and `2.17.3`

**Comment by mysticaltech** [comment]
@alexandradeas Please ping me again if it still happens in the latest version.
