### ISSUE TITLE
[Bug]: Problem installing new cluster

### ISSUE THREAD

**Issue by ulfgebhardt** [kube-hetzner/terraform-hcloud-kube-hetzner#1905]
### Description

After I had persistent network trouble, I decided to recreate my current staging cluster.

When deploying I get the following Errors in the `journalctl -f`
```
k3s.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: k3s.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Lightweight Kubernetes.
systemd[1]: k3s.service: Scheduled restart job immediately on client request, restart counter is at 3.
systemd[1]: Starting Lightweight Kubernetes...
k3s[4526]: time="2025-09-16T13:29:31Z" level=info msg="Starting k3s v1.31.12+k3s1 (2b53c7e4)"
k3s[4526]: time="2025-09-16T13:29:31Z" level=fatal msg="preparing server: failed to bootstrap cluster data: failed to check if bootstrap data has been initialized: failed to validate token: failed to get CA certs: Get \"https://10.255.0.101:6443/cacerts\": dial tcp 10.255.0.101:6443: connect: connection refused"
``` 

All 3 Control nodes have the same behaviour with different target IPs. Reason for it is a circular dependency on eachother.

When I manually edit the `/etc/rancher/k3s/config.yaml` on one maschine and remove `"server": "https://10.255.0.101:6443"`
The particular instance of k3s starts, but the peers, depending on it still fail with 

```
k3s.service: Scheduled restart job, restart counter is at 3.
systemd[1]: Starting Lightweight Kubernetes...
k3s[4818]: time="2025-09-16T13:31:57Z" level=info msg="Starting k3s v1.31.12+k3s1 (2b53c7e4)"
k3s[4818]: time="2025-09-16T13:31:57Z" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
k3s[4818]: time="2025-09-16T13:31:57Z" level=info msg="Managed etcd cluster not yet initialized"
k3s[4818]: time="2025-09-16T13:31:57Z" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
k3s[4818]: time="2025-09-16T13:31:57Z" level=fatal msg="preparing server: failed to bootstrap cluster data: etcd disabled"
systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: k3s.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Lightweight Kubernetes.
```

Tofu ends in:
```
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.agents["0-0-agent-large"],
│   on .terraform/modules/kube-hetzner/agents.tf line 145, in resource "null_resource" "agents":
│  145:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1644850627.sh": Process exited with status 124
╵
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.agents["0-1-agent-large"],
│   on .terraform/modules/kube-hetzner/agents.tf line 145, in resource "null_resource" "agents":
│  145:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_716466485.sh": Process exited with status 124
╵
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.control_planes["2-0-control-plane-nbg1"],
│   on .terraform/modules/kube-hetzner/control_planes.tf line 258, in resource "null_resource" "control_planes":
│  258:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_2147160905.sh": Process exited with status 124
╵
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.control_planes["4-0-control-plane-hel1"],
│   on .terraform/modules/kube-hetzner/control_planes.tf line 258, in resource "null_resource" "control_planes":
│  258:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1133324206.sh": Process exited with status 124
╵
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.control_planes["0-0-control-plane-fsn1"],
│   on .terraform/modules/kube-hetzner/control_planes.tf line 258, in resource "null_resource" "control_planes":
│  258:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_2008576245.sh": Process exited with status 124
```

Any help appreciated.

### Kube.tf file

```terraform
module "kube-hetzner" {
[...]
  source = "github.com/kube-hetzner/terraform-hcloud-kube-hetzner"

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cx22",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
   },
  {
      name        = "control-plane-nbg1",
      server_type = "cx22",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
  },
  {
      name        = "control-plane-hel1",
      server_type = "cx22",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1
   }
 ]
 agent_nodepools = [
   {
      name        = "agent-large",
      server_type = "cx32",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 2
    }
  ]

  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"
  kured_version = "1.19.0"
}
```

### Platform

Linux

**Comment by mysticaltech** [comment]
@ulfgebhardt Now fixed in v2.18.2 just released, terraform init -upgrade, and retry

**Comment by mysticaltech** [comment]
If that was not it, let me know, I will reopen.

**Comment by ulfgebhardt** [comment]
I still get cert errors after updating the version to latest master.

> `Journalctl -f` from subject control node
```
systemd[1]: k3s.service: Scheduled restart job immediately on client request, restart counter is at 2.
systemd[1]: Starting Lightweight Kubernetes...
k3s[3446]: time="2025-09-16T17:16:48Z" level=info msg="Starting k3s v1.31.12+k3s1 (2b53c7e4)"
k3s[3446]: time="2025-09-16T17:16:49Z" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
k3s[3446]: time="2025-09-16T17:16:49Z" level=info msg="Managed etcd cluster not yet initialized"
k3s[3446]: time="2025-09-16T17:16:49Z" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
k3s[3446]: time="2025-09-16T17:16:49Z" level=fatal msg="preparing server: failed to bootstrap cluster data: etcd disabled"
systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: k3s.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Lightweight Kubernetes.
``` 

Resulting in a timeout:

> `tofu apply` result
```
module.kube-hetzner.null_resource.control_planes["2-0-control-plane-nbg1"] (remote-exec): Waiting for the k3s server to start...
module.kube-hetzner.null_resource.control_planes["4-0-control-plane-hel1"]: Still creating... [6m30s elapsed]
module.kube-hetzner.null_resource.control_planes["2-0-control-plane-nbg1"]: Still creating... [6m30s elapsed]
module.kube-hetzner.null_resource.control_planes["4-0-control-plane-hel1"] (remote-exec): Waiting for the k3s server to start...
module.kube-hetzner.null_resource.control_planes["2-0-control-plane-nbg1"] (remote-exec): Waiting for the k3s server to start...
module.kube-hetzner.null_resource.control_planes["4-0-control-plane-hel1"] (remote-exec): Waiting for the k3s server to start...
module.kube-hetzner.null_resource.control_planes["2-0-control-plane-nbg1"] (remote-exec): Waiting for the k3s server to start...
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.control_planes["4-0-control-plane-hel1"],
│   on .terraform/modules/kube-hetzner/control_planes.tf line 258, in resource "null_resource" "control_planes":
│  258:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_976393586.sh": Process exited with status 124
╵
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.control_planes["2-0-control-plane-nbg1"],
│   on .terraform/modules/kube-hetzner/control_planes.tf line 258, in resource "null_resource" "control_planes":
│  258:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1904852933.sh": Process exited with status 124
╵
```

I had one control node running as a single node works.
This node has the following in `journalctl -f`
```
k3s[9981]: time="2025-09-16T17:22:21Z" level=warning msg="Received HTTP bootstrap request from 10.253.0.101:47412, but embedded etcd is not enabled."
k3s[9981]: time="2025-09-16T17:22:21Z" level=error msg="Sending HTTP/1.1 400 response to 10.253.0.101:47412: etcd disabled"
k3s[9981]: time="2025-09-16T17:22:22Z" level=warning msg="Received HTTP bootstrap request from 10.251.0.101:53356, but embedded etcd is not enabled."
k3s[9981]: time="2025-09-16T17:22:22Z" level=error msg="Sending HTTP/1.1 400 response to 10.251.0.101:53356: etcd disabled"
k3s[9981]: time="2025-09-16T17:22:27Z" level=warning msg="Received HTTP bootstrap request from 10.253.0.101:47496, but embedded etcd is not enabled."
```

Note: i updated kured to `1.20` as the newly merged PR allows that.

I will test starting without any node and setup all 3 from scratch now.

**Comment by ulfgebhardt** [comment]
When creating all 3 from scratch I still get the circular problem with a certificate error.

The problem remains unchanged for me.

Please help!

**Comment by ulfgebhardt** [comment]
When creating a cluster with 1 control node, that works for me.

If I then add another, this is in the tofu log:
```
module.kube-hetzner.null_resource.control_plane_config["0-0-control-plane-fsn1"] (remote-exec): Connected!
module.kube-hetzner.null_resource.control_plane_config["2-0-control-plane-nbg1"] (remote-exec): Connected!
module.kube-hetzner.null_resource.authentication_config["2-0-control-plane-nbg1"] (remote-exec): Updated authentication_config.yaml detected, restart of k3s service required
module.kube-hetzner.null_resource.authentication_config["2-0-control-plane-nbg1"] (remote-exec): No active k3s or k3s-agent service found
module.kube-hetzner.null_resource.authentication_config["2-0-control-plane-nbg1"] (remote-exec): k3s service or k3s-agent service (re)started successfully
module.kube-hetzner.null_resource.control_plane_config["0-0-control-plane-fsn1"] (remote-exec): Backing up /etc/rancher/k3s/config.yaml to /tmp/config_2025-09-16_17-56-01.yaml
module.kube-hetzner.null_resource.control_plane_config["0-0-control-plane-fsn1"] (remote-exec): Updated config.yaml detected, restart of k3s service required
module.kube-hetzner.null_resource.authentication_config["2-0-control-plane-nbg1"]: Creation complete after 4s [id=405580720780730142]
module.kube-hetzner.null_resource.control_plane_config["0-0-control-plane-fsn1"] (remote-exec): Job for k3s.service failed because the control process exited with error code.
module.kube-hetzner.null_resource.control_plane_config["0-0-control-plane-fsn1"] (remote-exec): See "systemctl status k3s.service" and "journalctl -xeu k3s.service" for details.
module.kube-hetzner.null_resource.control_plane_config["0-0-control-plane-fsn1"] (remote-exec): Error: Failed to restart k3s. Restoring /etc/rancher/k3s/config.yaml from backup
module.kube-hetzner.null_resource.control_plane_config["2-0-control-plane-nbg1"] (remote-exec): Updated config.yaml detected, restart of k3s service required
module.kube-hetzner.null_resource.control_plane_config["2-0-control-plane-nbg1"] (remote-exec): No active k3s or k3s-agent service found
module.kube-hetzner.null_resource.control_plane_config["2-0-control-plane-nbg1"] (remote-exec): k3s service or k3s-agent service (re)started successfully
```

meaning the existing node on fn1 gets an config update, fails and does a rollback of the config.

The tofu process is then stuck in the loop described in above posts.

I will try to dig out the error:

```
Stopping Lightweight Kubernetes...
systemd[1]: k3s.service: Deactivated successfully.
systemd[1]: k3s.service: Unit process 3966 (containerd-shim) remains running after unit stopped.
systemd[1]: k3s.service: Unit process 4456 (containerd-shim) remains running after unit stopped.
systemd[1]: k3s.service: Unit process 4482 (containerd-shim) remains running after unit stopped.
systemd[1]: k3s.service: Unit process 4540 (containerd-shim) remains running after unit stopped.
systemd[1]: k3s.service: Unit process 4558 (containerd-shim) remains running after unit stopped.
systemd[1]: Stopped Lightweight Kubernetes.
systemd[1]: k3s.service: Consumed 2min 20.477s CPU time.
systemd[1]: k3s.service: Found left-over process 3966 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: k3s.service: Found left-over process 4456 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: k3s.service: Found left-over process 4482 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: k3s.service: Found left-over process 4540 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: k3s.service: Found left-over process 4558 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: Starting Lightweight Kubernetes...
systemd[1]: k3s.service: Found left-over process 3966 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: k3s.service: Found left-over process 4456 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: k3s.service: Found left-over process 4482 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: k3s.service: Found left-over process 4540 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
systemd[1]: k3s.service: Found left-over process 4558 (containerd-shim) in control group while start>
systemd[1]: k3s.service: This usually indicates unclean termination of a previous run, or service im>
k3s[9368]: time="2025-09-16T18:09:33Z" level=info msg="Starting k3s v1.31.12+k3s1 (2b53c7e4)"
k3s[9368]: time="2025-09-16T18:09:33Z" level=info msg="Managed etcd cluster not yet initialized"
k3s[9368]: time="2025-09-16T18:09:33Z" level=warning msg="Skipping cluster configuration validation: Get \"https://10.254.0.101:6443/v1-k3s/config\": dial tcp 10.254.0.101:6443: connect: connection refused"
k3s[9368]: time="2025-09-16T18:09:33Z" level=fatal msg="preparing server: failed to bootstrap cluster data: Get \"https://10.254.0.101:6443/v1-k3s/server-bootstrap\": dial tcp 10.254.0.101:6443: connect: connection refused"
systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: k3s.service: Failed with result 'exit-code'.
systemd[1]: k3s.service: Unit process 3966 (containerd-shim) remains running after unit stopped.
systemd[1]: k3s.service: Unit process 4456 (containerd-shim) remains running after unit stopped.
systemd[1]: k3s.service: Unit process 4482 (containerd-shim) remains running after unit stopped.
systemd[1]: k3s.service: Unit process 4540 (containerd-shim) remains running after unit stopped.
systemd[1]: k3s.service: Unit process 4558 (containerd-shim) remains running after unit stopped.
systemd[1]: Failed to start Lightweight Kubernetes.
systemd[1]: Stopped Lightweight Kubernetes.
```

So the control-node cannot connect to the other node. Most likely because itself cannot start as its stuck in a loop.

**Comment by ulfgebhardt** [comment]
Can you reopen @mysticaltech ?

**Comment by ulfgebhardt** [comment]
I found that even when starting from scratch and with 3 control nodes the problem persists.

I found a solution however:

The problem seems to be, that the master-node is using an sqlite storage. This is incompatible with multiple control nodes.
For that scenario `etcd` is required.
Etcd is part of k3s but does not get properly initialized on my end.

To fix this I ssh into the machine dedicated as master node (all others point to it in `/etc/rancher/k3s/config.yaml -> server`).
I then stop the k3s service and start it manually with the cluster-init command:
```bash
> systemctl stop k3s
> k3s server --cluster-init
(wait a bit till some syncing is done)
> (ctrl+c)
> systemctl start k3s
```

After this i can `tofu apply` and things go green.

<img width="611" height="92" alt="Image" src="https://github.com/user-attachments/assets/294485be-202d-40d1-ae3d-4bc53936dc81" />

As I stated above this persists on my end when creating a new cluster with nothing in it.

Please try to check if you can reproduce - maybe we can find out where the cluster init goes wrong and fix this.

**Comment by ulfgebhardt** [comment]
closing as resolvable via described method - not fully solved tho.

**Comment by mysticaltech** [comment]
Glad it worked, but we don't use sqlite huh. Next time, always best to terraform destroy before retrying.
